liip_imagine:
    driver: "gd"
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~
        toto:
            quality: 100
            filters:
                thumbnail: { size: [1000, 1000], mode: outbound }