liip_imagine:
    driver: "gd"
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~
        toto:
            quality: 75
            filters:
                thumbnail: { size: [500, 800], mode: outbound }